version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: audit_postgres
    environment:
      POSTGRES_DB: audit_db
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "5432:5432"
    volumes:
      - audit_pgdata:/var/lib/postgresql/data
      - ./src/traceability:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test"]
      interval: 5s
      retries: 5

volumes:
  audit_pgdata:
